package com.univ.UI;

import com.univ.DAO.productDAO;
import com.univ.DTO.productDTO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author IT
 */
public class product extends javax.swing.JFrame {

    private boolean validateField()
    {
        if(product_name.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(product.this,"enter product name");
            product_name.grabFocus();
            return false;
        }
        if(purchase_price.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(product.this,"enter product purchase price");
            purchase_price.grabFocus();
            return false;
        }
        if(sale_price.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(product.this,"enter product sale price");
            sale_price.grabFocus();
            return false;
        }
    return true;    
    }
    
    public product() {
        initComponents();
        setSize(500,400);
        setLocationRelativeTo(null);
    }
     int count=1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        product_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        purchase_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sale_price = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        savemsg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Product Detail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 180, 30));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_idActionPerformed(evt);
            }
        });
        getContentPane().add(product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 50, 30));

        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, -1));
        getContentPane().add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 30));

        jLabel4.setText("Purchase Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));
        getContentPane().add(purchase_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 210, 30));

        jLabel5.setText("Sale Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 210, 70, -1));
        getContentPane().add(sale_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 210, 30));

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jButton1.setText("search");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jButton2.setText("update");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jButton3.setText("delete");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel6.setText("(only for search,delete,update)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, -1));

        savemsg.setText("save status");
        getContentPane().add(savemsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 20));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, -1));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 41, -1));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 48, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       
        if(validateField())
        {
        productDTO dto=new productDTO();
        dto.setProduct_name(product_name.getText());
        dto.setPurchase_price(Integer.parseInt(purchase_price.getText()));
        dto.setSale_price(Integer.parseInt(sale_price.getText()));

       
        productDAO dao=new productDAO();
        int x=dao.insert(dto);
        
        if(x==1)
        {
        savemsg.setText(count+"data inserted");
        product_name.setText("");
        purchase_price.setText("");
        sale_price.setText("");
        count++;
        }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField purchase_price;
    private javax.swing.JTextField sale_price;
    private javax.swing.JButton save;
    private javax.swing.JLabel savemsg;
    // End of variables declaration//GEN-END:variables
}
