/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.univ.UI;

import com.univ.DAO.purchaseDAO;
import com.univ.DTO.purchaseDTO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;


public class purchase extends javax.swing.JFrame {

    Vector v1,v2,v3,c1,c2;
    String invno;
    int pid,cid;
    public void purchaseForm()
    {
        //get invno number
        purchaseDAO dao=new purchaseDAO();
         invno=dao.getInvNo();
        invno1.setText(invno);
        
        //get product
        List t1=dao.getproduct();
        v1=(Vector) t1.get(0);
        v2=(Vector) t1.get(1);
        v3=(Vector) t1.get(2);
        for(int i=0;i<v2.size();i++)
        {
            prod1.addItem((String)v2.get(i));
        }
        
        //get customer
        List t2=dao.getCustomer();
        c1=(Vector) t2.get(0);
        c2=(Vector) t2.get(1);
        for(int i=0;i<c2.size();i++)
        {
            cust.addItem((String)c2.get(i));
        }
    }
     private boolean validateField()
    {
         if(qty.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(purchase.this,"enter product Quantity");
            qty.grabFocus();
            return false;
        }
  
    return true;    
    }
    
    public purchase() {
        initComponents();
        setSize(500,500);
        purchaseForm();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String date = df.format(new Date());
        date1.setText(date);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        invno1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        purchaseid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        savemsg = new javax.swing.JLabel();
        prod1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        prprice1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cust = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Purchase Detail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 81, -1));

        invno1.setEditable(false);
        invno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invno1ActionPerformed(evt);
            }
        });
        getContentPane().add(invno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, 30));

        jLabel3.setText("Purchase Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        jLabel7.setText("Inv. No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        getContentPane().add(purchaseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, 30));

        jLabel8.setText("(only for search,delete,update)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, -1));

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 30));

        savemsg.setText("save status");
        getContentPane().add(savemsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 80, -1));

        prod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod1ActionPerformed(evt);
            }
        });
        getContentPane().add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 30));

        jLabel2.setText("product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, -1));

        prprice1.setEditable(false);
        getContentPane().add(prprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 90, 30));

        jLabel4.setText("purchase price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, -1));

        cust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        getContentPane().add(cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, 30));

        jLabel5.setText("customer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, -1));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 30));

        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, -1));

        date1.setEditable(false);
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 90, 30));

        jLabel9.setText("Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invno1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      if(validateField())
      {
        purchaseDTO dto =new purchaseDTO();
        dto.setInv_no(invno);//set inv no
        // product id
        int x=prod1.getSelectedIndex();
        int y=(int) v1.get(x-1);
        dto.setProduct_id(y);
        //customer id
        int x1=cust.getSelectedIndex();
        int y1=(int)c1.get(x1-1);
        dto.setCustomer_id(y1);
        //Quantity
        int q=Integer.parseInt(qty.getText());
        dto.setQuantity(q);
        //Totol price
        int pp=Integer.parseInt(prprice1.getText());
        pp=pp*q;
        dto.setTotal_amount(pp);
        //set date
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String date = df.format(new Date());
        dto.setPurchase_date(date);
        purchaseDAO dao=new purchaseDAO();
        int r=dao.insert(dto);
        if(r==1)
        {
            savemsg.setText(r+" data inserted");
        }
      } 
    }//GEN-LAST:event_saveActionPerformed

    private void prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod1ActionPerformed
        int x=prod1.getSelectedIndex();
        int y=(int) v3.get(x-1);
        prprice1.setText(y+"");
    }//GEN-LAST:event_prod1ActionPerformed

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
        int n=Integer.parseInt(qty.getText());
        try{
        if(n<1)
        {
            JOptionPane.showMessageDialog(null,"can not be less than 1");
        }
        }catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_qtyKeyReleased

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyKeyTyped

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cust;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField invno1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> prod1;
    private javax.swing.JTextField prprice1;
    private javax.swing.JTextField purchaseid;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JLabel savemsg;
    // End of variables declaration//GEN-END:variables
}
