/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.univ.UI;

import com.univ.DAO.purchaseDAO;
import com.univ.DAO.reportDAO;
import com.univ.DAO.salesDAO;
import java.sql.ResultSet;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IT
 */
public class report extends javax.swing.JFrame {

    Vector v1,v2;
    ResultSet rs1=null;
    DefaultTableModel model,model1,model2;
    public void purchaseForm()
    {

        purchaseDAO dao=new purchaseDAO();
        //get product
        List t1=dao.getproductreport();
        v1=(Vector) t1.get(0);
        v2=(Vector) t1.get(1);
        for(int i=0;i<v2.size();i++)
        {
            prod1.addItem((String)v2.get(i));
        }
        
   
    }
    public report() {
        initComponents();
        setSize(700,500);
        setLocationRelativeTo(null);
        purchaseForm();
        model= (DefaultTableModel) tb1Data.getModel();
        model1= (DefaultTableModel) tb2data.getModel();
        model2= (DefaultTableModel) tb3data.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prod1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3data = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb2data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tup = new javax.swing.JTextField();
        tus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selecttype = new javax.swing.JComboBox<>();
        cusname = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod1ActionPerformed(evt);
            }
        });
        getContentPane().add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, -1));

        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "In Stock"
            }
        ));
        jScrollPane2.setViewportView(tb1Data);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 270, 50));

        tb3data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale Quantity", "Sale Date"
            }
        ));
        jScrollPane3.setViewportView(tb3data);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, 200));

        tb2data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase Quantity", "Purchase Date"
            }
        ));
        jScrollPane4.setViewportView(tb2data);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 200));

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 53, 90, 30));

        tup.setEditable(false);
        getContentPane().add(tup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 30));

        tus.setEditable(false);
        getContentPane().add(tus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Total Unit Purchased");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Total unit sold");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 110, -1));

        selecttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        selecttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecttypeActionPerformed(evt);
            }
        });
        getContentPane().add(selecttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 80, 30));

        getContentPane().add(cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 80, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Customer Detail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel5.setText("Select Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 70, -1));

        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod1ActionPerformed
        int x=prod1.getSelectedIndex();
        int y=(int) v1.get(x-1);
        reportDAO dao=new reportDAO();
        int stock=dao.getStock(y);
        //inserting data inti 1st table
        model.insertRow(tb1Data.getRowCount(),new Object[]{
            y,stock
        });
     //getting data from purchase table
        ResultSet rs=dao.getpurchase(y);
       
        try
        {
        int tup1=0;    
        while(rs.next())
        {
           tup1=tup1+rs.getInt(1);//for total unit purchased
           model1.insertRow(tb2data.getRowCount(),new Object[]{
            rs.getInt(1),
            rs.getString(2)
        });
        }
        //setting total unit purchase
        tup.setText(tup1+"");
        
        }catch(Exception ee)
        {
            System.out.println(ee);
        }
        

        
        //getting data from sale table
        ResultSet rs1=dao.getsale(y);
       
        try{
        int tus1=0;
        while(rs1.next())
        {
            tus1=tus1+rs1.getInt(1);
           model2.insertRow(tb3data.getRowCount(),new Object[]{
            rs1.getInt(1),
            rs1.getString(2)
        });
        }
        tus.setText(tus1+"");
        }catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_prod1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        model.setRowCount(0);
        model1.setRowCount(0);
        model2.setRowCount(0);
        tup.setText("");
        tus.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selecttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecttypeActionPerformed
        int x=selecttype.getSelectedIndex();
        if(x==0)
        {
            
            Vector c1,c2;
            purchaseDAO dao=new purchaseDAO();
            List t2=dao.getCustomer();
            c1=(Vector) t2.get(0);
            c2=(Vector) t2.get(1);
        for(int i=0;i<c2.size();i++)
        {
            cusname.addItem((String)c2.get(i));
        }
  
        for(int i=0;i<v2.size();i++)
        {
            prod1.addItem((String)v2.get(i));
        }
            
        }
        else
        {
             Vector c1,c2;
            salesDAO dao=new salesDAO();
            List t2=dao.getCustomer();
            c1=(Vector) t2.get(0);
            c2=(Vector) t2.get(1);
            for(int i=0;i<c2.size();i++)
            {
                cusname.addItem((String)c2.get(i));
            }
        }
    }//GEN-LAST:event_selecttypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cusname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> prod1;
    private javax.swing.JComboBox<String> selecttype;
    private javax.swing.JTable tb1Data;
    private javax.swing.JTable tb2data;
    private javax.swing.JTable tb3data;
    private javax.swing.JTextField tup;
    private javax.swing.JTextField tus;
    // End of variables declaration//GEN-END:variables
}
