/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.univ.UI;

import com.univ.DAO.salesDAO;
import com.univ.DB.DBConnection;
import com.univ.DTO.salesDTO;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;



/**
 *
 * @author IT
 */
public class sales extends javax.swing.JFrame {
    
    Vector v1,v2,v3,c1,c2;
    String invno;
    int pid,cid;
    public void SaleForm()
    {
        //get invno number
        salesDAO dao=new salesDAO();
         invno=dao.getInvNo();
        invno1.setText(invno);
        
        //get product
        List t1=dao.getproduct();
        v1=(Vector) t1.get(0);
        v2=(Vector) t1.get(1);
        v3=(Vector) t1.get(2);
        for(int i=0;i<v2.size();i++)
        {
            prod1.addItem((String)v2.get(i));
        }
        
        //get customer
        List t2=dao.getCustomer();
        c1=(Vector) t2.get(0);
        c2=(Vector) t2.get(1);
        for(int i=0;i<c2.size();i++)
        {
            cust.addItem((String)c2.get(i));
        }
    }
         private boolean validateField()
    {
         if(qty.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(sales.this,"enter product Quantity");
            qty.grabFocus();
            return false;
        }
  
    return true;    
    }
    public sales() {
        initComponents();
        setSize(400,400);
         SaleForm();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String date = df.format(new Date());
        date1.setText(date);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        invno1 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        savemsg = new javax.swing.JLabel();
        cust = new javax.swing.JComboBox<>();
        prod1 = new javax.swing.JComboBox<>();
        prprice1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sales Detail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, -1));

        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));

        jLabel3.setText("Sale Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        jLabel4.setText("Product Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, -1));

        jLabel7.setText("Inv. No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, -1));

        jLabel8.setText("Customer ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        invno1.setEditable(false);
        getContentPane().add(invno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 30));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, 30));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 30));

        date1.setEditable(false);
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, 30));

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 30));

        savemsg.setText("save status");
        getContentPane().add(savemsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 70, -1));

        cust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        getContentPane().add(cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, 30));

        prod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod1ActionPerformed(evt);
            }
        });
        getContentPane().add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, 30));

        prprice1.setEditable(false);
        getContentPane().add(prprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 90, 30));

        jLabel9.setText("purchase price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed

    }//GEN-LAST:event_qtyActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(validateField())
        {
        salesDTO dto =new salesDTO();
        dto.setInv_no(invno);//set inv no
        // product id
        int x=prod1.getSelectedIndex();
        int y=(int) v1.get(x-1);
        dto.setProduct_id(y);
        //customer id
        int x1=cust.getSelectedIndex();
        int y1=(int)c1.get(x1-1);
        dto.setCustomer_id(y1);
        //Quantity
        int q=Integer.parseInt(qty.getText());
        dto.setQuantity(q);
        //Totol price
        int pp=Integer.parseInt(prprice1.getText());
        pp=pp*q;
        dto.setTotal_amount(pp);
        //set date
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String date = df.format(new Date());
        dto.setSale_date(date);
        salesDAO dao=new salesDAO();
        int r=dao.insert(dto);
        
       
         try
         {
             if(r==1)
            {
                Connection con1=DBConnection.getConn();
                Statement stm=con1.createStatement();
                ResultSet rs= stm.executeQuery("select qty from stock where product_id="+y);
                int old=0;
                if(rs.next())
                {
                    old=rs.getInt(1);
                }
                int nw=old-q;  
                PreparedStatement ps=con1.prepareStatement("update stock set qty=? where product_id="+y);
                ps.setInt(1,nw);
                int n=ps.executeUpdate();
                if(n==1)
                {
                 System.out.println("quantity updated in stock also");
                }
            }else
            {
               System.out.println("quantity  not updated in stock");
            }
        
         }catch(Exception ee)
         {
             System.out.println(ee);
         }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod1ActionPerformed
        int x=prod1.getSelectedIndex();
        int y=(int) v3.get(x-1);
        prprice1.setText(y+"");
    }//GEN-LAST:event_prod1ActionPerformed

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
             
        try
        {
            int q=Integer.parseInt(qty.getText());
            int x=prod1.getSelectedIndex();
            int y=(int) v1.get(x-1);
            Connection con1=DBConnection.getConn();
            Statement stm=con1.createStatement();
            ResultSet rs= stm.executeQuery("select qty from stock where product_id="+y);
            int old=0;
            if(rs.next())
            {
                old=rs.getInt(1);
            }
            int nw=old-q;
            if(nw<0)
            {
                 JOptionPane.showMessageDialog(null, "only "+old+" in stock");
            }
            
        }catch(Exception ee)
        {
            System.out.println(ee);
        }
    }//GEN-LAST:event_qtyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cust;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField invno1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JComboBox<String> prod1;
    private javax.swing.JTextField prprice1;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JLabel savemsg;
    // End of variables declaration//GEN-END:variables
}
